version: "3"
services:
    go:
      build: .
      tty: true
      ports:
        - "8088:8080"
      volumes:
        - type: bind
          source: "./sql/item.db"
          target: /var/lib/sql/item.db
    vue:
      build: 
        context: .
        dockerfile: ./frontend/Dockerfile
      tty: true
      ports:
        - "8089:80"