version: "3"
services:
    go:
      build: .
      tty: true
      env_file: ./.env
      environment:
        - PORT
        - DRIVER
        - DSN
      ports:
        - ${PORT}:${PORT}
    vue:
      build: 
        context: .
        dockerfile: ./frontend/Dockerfile
      tty: true
      ports:
        - "8089:80"
    db:
      image: mariadb
      container_name: db
      environment:
        - MYSQL_ROOT_PASSWORD
        - MYSQL_DATABASE
        - TZ
      command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      volumes:
        - ./mysql/initdb.d:/docker-entrypoint-initdb.d
        - gorl-db:/var/lib/mysql/gorl
      ports:
        - 3306:3306

volumes:
  gorl-db:
    driver: local
