version: "3"
services:
    go:
      build: .
      tty: true
      ports:
        - "8080:8080"
      volumes:
        - ./:/go/app
    vue:
      build: 
        context: .
        dockerfile: ./frontend/Dockerfile
      tty: true
      ports:
        - "8089:80"
